logging:
  level:
    root: WARN
    de.eblaas.museum: INFO

spring:
  profiles:
    active: dev,import
  main:
    banner-mode: "off"
---
import:
  size: -1
  filepath: /data/MetObjects.csv
spring:
  profiles: dev
  datasource:
    url: "jdbc:h2:mem:museum:"
    driverClassName: org.h2.Driver


---
import:
  size: -1
  filepath: /data/MetObjects.csv
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://postgresql-service:5432/postgres
    username: ''
    password: ''
    hikari:
      maximum-pool-size: 10

